### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by naeemshaikh90** [aleksandrshoshiashvili/AwesomeSpotlightView#1]
Will you please provide CocoaPods support? https://github.com/aleksandrshoshiashvili/AwesomeSpotlightView/commit/9404ece60b0b9504994eb83144aa276fceab5a75

**Comment by naeemshaikh90** [comment]
https://github.com/vsouza/awesome-ios/issues/1499

**Comment by aleksandrshoshiashvili** [comment]
Done
