### ISSUE TITLE
Setting spotlightMaskColor has no effect

### ISSUE THREAD

**Issue by markst** [aleksandrshoshiashvili/AwesomeSpotlightView#11]
Since the `spotlightMask` fill colour is only set on `setupMask()` which in turn is only triggered by `init(frame` there is no way to set the spotlight mask colour.

**Comment by markst** [comment]
workaround might be to add: 
```swift
spotlightMask.fillColor = spotlightMaskColor.cgColor
```
within the `start()` function. 
otherwise could use property observer `didSet`
```swift
public var spotlightMaskColor = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.6) {
    didSet{
        spotlightMask.fillColor = spotlightMaskColor.cgColor
    }
}
```

**Comment by aleksandrshoshiashvili** [comment]
@markst, finally fix it. Thank you so much for support and improving this library :)
