### ISSUE TITLE
Podspecs not updated correctly

### ISSUE THREAD

**Issue by lukeharries** [aleksandrshoshiashvili/AwesomeSpotlightView#14]
The podspecs for versions above 0.1.4 have not been updated correctly.

Versions 0.1.5 through to 0.1.8 are still pointing to the 0.1.4 release tag:
```
"source": {
    "git": "https://github.com/aleksandrshoshiashvili/AwesomeSpotlightView.git",
    "tag": "0.1.4"
  },
```

And version 0.1.8 does not correctly specify that it is to be build with Swift 4:
```
  "pushed_with_swift_version": "3.0"
```

You can see the published pod spec for 0.1.8 here: [https://github.com/CocoaPods/Specs/blob/master/Specs/1/1/5/AwesomeSpotlightView/0.1.8/AwesomeSpotlightView.podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/1/1/5/AwesomeSpotlightView/0.1.8/AwesomeSpotlightView.podspec.json)

**Comment by aleksandrshoshiashvili** [comment]
@lukeharries I have updated podspec and fixed the bug
