### ISSUE TITLE
object-c usage sample

### ISSUE THREAD

**Issue by ipad4** [aleksandrshoshiashvili/AwesomeSpotlightView#16]
suport object-c?

**Comment by aleksandrshoshiashvili** [comment]
`AwesomeSpotlightView` written in Swift, but you still can use it in objective-c projects:

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

the `Importing Swift into Objective-C` section gives instructions on how to do this.
