### ISSUE TITLE
Feature Request : Extra margin parameter for circles

### ISSUE THREAD

**Issue by ergunkocak** [aleksandrshoshiashvili/AwesomeSpotlightView#2]
Hello,

First of of thanks a lot for such useful library 👍 

For images "Circle" mode just covers the borders of image that would be great if we can define extra margin for the circle around the item so it can be bigger

Cheers

**Comment by aleksandrshoshiashvili** [comment]
Hello, @ergunkocak  

Thanks for the feedback. I added a _margin_ parameter to the class _AwesomeSpotlight_, so you can set margin for all spotlights you need. Check out the new demo _AwesomeSpotlightViewDemo_.
