### ISSUE TITLE
can i use this in objective-c project?

### ISSUE THREAD

**Issue by suhasPathakChoice** [aleksandrshoshiashvili/AwesomeSpotlightView#20]

**Comment by aleksandrshoshiashvili** [comment]
@suhasPathakChoice `AwesomeSpotlightView` written in Swift, but you still can use it in objective-c projects:

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

the `Importing Swift into Objective-C` section gives instructions on how to do this.

#16
