### ISSUE TITLE
Show spotlight by specifying with index

### ISSUE THREAD

**Issue by rizumita** [aleksandrshoshiashvili/AwesomeSpotlightView#23]
I want AwesomeSpotlightView to show a spotlight by specifying with index.
Could you change `goToSpotlightAtIndex(index: Int)' method to public?

**Comment by aleksandrshoshiashvili** [comment]
@rizumita Thanks for this suggestion! I've added new public method: `start(fromIndex index: Int)`. It's available in the version 0.1.8.
