### ISSUE TITLE
AwesomeSpotlightViewDelegate memory leak

### ISSUE THREAD

**Issue by emresa37** [aleksandrshoshiashvili/AwesomeSpotlightView#25]
AwesomeSpotlightView at line 23

You guys are need to declare delegate as weak variable. It's causing memory leak.

**Comment by aleksandrshoshiashvili** [comment]
@emresa37 very good point. I will fix it asap

**Comment by aleksandrshoshiashvili** [comment]
@emresa37 I've fixed it, you can check version 0.1.8. Thanks for pointing out this issue!

**Comment by emresa37** [comment]
welcome. Thank you 👍
