### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by DavidDHansson** [aleksandrshoshiashvili/AwesomeSpotlightView#27]
Add support for Swift Package Manager

**Comment by JMCPH** [comment]
+1 Would be highly valuable to be able to add this through SPM @aleksandrshoshiashvili

**Comment by aleksandrshoshiashvili** [comment]
Hey @DavidDHansson @JMCPH 👋 

I have added support for Swift Package Manager, so you can use AwesomeSpotlightView via SPM. Instructions are added to ReadMe file. Let me know you will have any issues with it.
