### ISSUE TITLE
Possible to enable user interaction within the spotlight?

### ISSUE THREAD

**Issue by aabosh** [aleksandrshoshiashvili/AwesomeSpotlightView#3]
Hi,

I'm loving this library and have been using it for my new app.

Currently, I spotlight a view I want my user to tap, but he has to tap twice in order to first dismiss the spotlight view. Is it possible to enable user interaction within the spotlight so I can eliminate the first tap?

Thank you,
Andrew

**Comment by aleksandrshoshiashvili** [comment]
Hi, thanks for feedback! And sorry for the long response.

So, you want handle user interaction with spotlight? I think new delegate method and method for dismiss spotlight can solve this problem, am i correct? If yes, i add it ASAP.

**Comment by aabosh** [comment]
No worries about the delay!

Yep, I think we're on the same page.
If it could handle user interaction out out the box with no delegates, that would be even better. However, I'm cool with your solution too.

Thank you so much!

**Comment by aleksandrshoshiashvili** [comment]
@aabosh, Good news: i have not forgotten about you and upgrade AwesomeSpotlightView. I hope it will help to you. 

So, now you can use the property `isAllowPassTouchesThroughSpotlight` for your goal: if you set `true`, touch will be pass through spotlight to view below and then SpotlightView will disappear. (note, that `isAllowPassTouchesThroughSpotlight` default `false`).

You can see it in action in Demo: `handleShowAction`  show SpotlightView with `isAllowPassTouchesThroughSpotlight = true`

**Comment by aabosh** [comment]
Nice! Works quite well, thanks for the update.

Two things though:

1. I feel the fade out should still occur when `isAllowPassTouchesThroughSpotlight ` is `true`.
2. It may make more sense to have the `isAllowPassTouchesThroughSpotlight` property on `AwesomeSpotlight` rather than `AwesomeSpotlightView`, as I personally only enable the property for some spotlights, which I'm currently checking and doing in the `willNavigateToIndex` function. It would be cleaner if it was a property under  `AwesomeSpotlight`.

Thanks again, I really appreciate your work!

**Comment by aleksandrshoshiashvili** [comment]
@aabosh Thanks for the comments. Sounds reasonable. I tried to take them into account in the new commit. You can see changes in the demo app.

**Comment by aabosh** [comment]
Super sorry about the late response! I've had a busy week. I just had a chance to try out the updated code and it's perfect, thank you so much for the quick responses and overall great library.
